-- 005: 유국만관 (流し満貫) 자리별 추적
ALTER TABLE hand_results
  ADD COLUMN IF NOT EXISTS nagashi_e BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS nagashi_s BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS nagashi_w BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS nagashi_n BOOLEAN NOT NULL DEFAULT FALSE;
